### ISSUE TITLE
Fallen Maia created in character creator are turned into Orcs in game

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#174]
Pretty minor really - could just remove them as options to create.

https://discord.com/channels/751097183448727552/778645689089392730/878972014575099904

**Comment by jj248** [comment]
Turns out you can't disable cultures, so have added clause to the conversion event trigger to ignore ruler designer characters.

**Comment by Remerod** [comment]
I'm not 100 sure what's being asked here, (especially since i don't have acess to all discord channel links, and i have a hard time connecting discord to my webpage). But if you wanted to test out that the culture change to orc, that seems to be working. 
Altough, i added the maia trait to the character i made, and that stayed, maybe that's also something to consider un-enabling? (along with istari & similar). 

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150681083-69753415-6f44-4ac3-a308-1f11cc23a6fa.png)

![image](https://user-images.githubusercontent.com/79544635/150681099-bb073043-b1c5-4ca6-8d27-a2a067e2a8fe.png)

</details>

**Comment by JukeJukestar** [comment]
I disagree because the player should be free to play as a custom wizard or god if they so choose

it only impacts the game if the player deliberately uses it so theres no reason not to give them that option

**Comment by Remerod** [comment]
> Simply that if you create a character in Ruler Designer that is a Fallen Maia or Fallen Istari, that they remain so and are not converted to an orc within the first year or two. 🙂

-Jamie

Been testing 3 custom created characters for around 4 years with the maia and istari traits, they remained there culture and don't switch to orcs culture. This issue should be done with this.
