### ISSUE TITLE
Sailing Activity

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#194]
Implement sailing activity with fleshed out exploration and piracy branches.

**Comment by JukeJukestar** [comment]
Stuff to consider:

- Mariner trait experience gain from sailing event, if possible it would be great to also get a small ammount of experience from leading an embarked army so its integrated with regular raiding gameplay)

- set sail activity should loose mariner characters more stress. but nerf the base stress loss a bit

- Pirate tradition tenet should consider mariner trait a virtue (although they have a lot of virtues and sins already. Also, maybe Greedy shouldnt be a virtue for pirates as greedy captains arent exactly well liked)
(maybe work on this after culture rework instead since its probably gonna become cultural)

- random event for tier 3 mariner rulers to teach their ward the level 1 mariner trait

- possibly put the decision below "Call hunt" so its more in line with the other two stress loss decision

**Comment by RedArkady** [comment]
Unless we have volunteers to do a southern branch of sailing events we can probably consider closing this now - we have tonnes of events and a separate Git issue in the testing column for all the new stuff. If we do want a southern branch at some point then a new issue could be created specifically for that?

**Comment by JukeJukestar** [comment]
![unknown](https://user-images.githubusercontent.com/76008882/164793631-6c587fa1-b1e0-4ecc-97f2-a9ee8ebc6780.png)

When you get the Lossoth Trading event while sailing, it says "your words are ineffective" even if you succeed
