### ISSUE TITLE
Addition of two new religions for Arysis and Lurmsakun

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#195]
As Khaz Gramaze is a little too large right now!

**Comment by jj248** [comment]
Added - just need to add a new Sacred Waters tenet.

**Comment by jj248** [comment]
Tenet added.  Also have added Mariner lifestyle trait to Primacy of Ulmo and Blood of Numenor to Memory of Akallabeth.  Ready to test.

**Comment by jj248** [comment]
![image](https://user-images.githubusercontent.com/26043074/146529529-2aadfe73-f354-4a4b-aecf-31090038045f.png)

**Comment by Remerod** [comment]
Had a look on Cult of Makusset in game.
I'm not familiar with the lore for this cult, but i felt it to be both thematic and fitting for it's place. I have some feedback on it thought, both lore wise and balance wise, even though the latter is not my strongest forte 

* For a religion considered to be open and enlighten, they sure have strict crime doctrines, and I find it kind of find it funny that adultery is criminal and being chaste is of the sins 

* Other minor Religions like Gurzilikä and Maladûmite have only like 3 holy sites, while Cult of Makusset have 5, very close togather, unless there is a lore reason for this i would limit it to 3 since this feel like a minor religion, I would take away Sâlizhat and either Nênadija or Nênari to have a good spread among the holy sites.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/146603909-e13b5bda-cb7a-4b4c-981e-088c8c7f1285.png)

</details>

**Comment by jj248** [comment]
Rolling into #159
