### ISSUE TITLE
Complete Tedjin event chains and decisions

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#208]

**Comment by JukeJukestar** [comment]
Tedjin Review and Early Notes:

I have only played a few games as the Tedjin so far, havent been able to find any bugs yet but I see some big balancing problems.

**Balancing**

Biggest Issue right off the bat is that your personal starting domain and expansion options are bad. You start with a good domain limit, but you only hold two counties at the beginning (which after inheritance are still the wrong culture, giving a further malus to tax and levy) I have serious problems supporting even the initial unupgraded army because I have so little gold and cant raid to make more.
Your only good options for increasing your holdings are your two Soriyan vassals, one of which is in your dejure duchy;
Duke vassal of Dhajran, but getting claims on him and taking his titles is going to be hard in the early game;
Your Duke vassal of Kes Ebb, same issue as getting claims and taking his titles will take a long while.

Essentially. you will not be able to increase your domain before the civil war, unless you get lucky and manage to conquer something before your father dies.

Azumen on the other hand has 3-5 counties depending on wether he conquered the independent dejure count in his duchy.
Personal domain makes out the bulk of your strength, with vassals only giving little tax and levy overall.

Making the starting holdings better by giving more buildings (and possibly converting the temple in your capital into a barony) seems logical, but even then your income and levy will be too little to accomplish much. If you go any route other than the civil war (in which the free event troops are the bulk of your forces) and after the civil war you will constantly have this issue.


**The Moderate Route**

The moderate route is in my opinion the strongest one, as I was able to, with some swaying and a few gifts, convince all of the Eastern lords to convert, with only the two western lords in dejure Tedja refusing initially. Typically Azumen will still try to revolt for independence, which he did win in my first playthrough, but although not easy winning against him is most likely possible.
Your holdings are bad, but if you take your time fabricating claims (good luck getting the cash for that haha) you will eventually get a decent ammount of holdings once you take some from your vassals

**The Civil War Route**

(testing ongoing)

**Comment by jj248** [comment]
Have made the following balancing tweaks - feedback would be great:

- Improved the holdings in some of Bor's lands

- Tedjin reformer modifier now gives -20 vassal opinion, +40 same faith opinion. (down from -30 / +60 )

- Bor is now a holy warrior

- Ayal should now die sometime between 300 to 900 days after game start.

**Comment by JukeJukestar** [comment]
One thing I didnt realize in my first two games is how good the chances of vassals offering you a deal if you ask them to convert are. even with "might convert" and -30 opinion, two vassals accepted in exchange for a favor

**Comment by jj248** [comment]
Pretty sure I know the cause. Will fix tonight.

**Comment by JukeJukestar** [comment]
With the way its balanced for the reformist civil war, have the end of the civil war revoke all of Azumens titles and give them to you. This way the AI wont struggle with revoking counties and you wont get tyranny because you can only revoke a certain ammount of them after someone was a traitor.

This way you have a good ammount of holdings and are ready to expand the tedjin

**Comment by jj248** [comment]
Implemented Juke's suggestion to revoke Azumen's lands on defeat.  Closing issue.
