### ISSUE TITLE
Abrakhân Missions

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#217]
### Beta-test Notes
The purpose of the Abrakhân missions is a feature to guide the player at their own pace and direction through the subjugation of Harad. It starts off with a couple of events and is content heavy, yet after Nâfarat there’s currently no themed and just unlocked Decisions (the missions) and a generic event once you do finish a Decision.
A mission refers to the whole event–decision chain.
### To look out for:
•	Do the missions make sense to the player? Such as, once you’ve conquered the Dune Sea, a couple of other missions open.
•	Are the rewards worth the time and fair?
•	What time frame do you estimate Abrakhân completing all the missions minus Umbar and Near Harad in the hands of a competent player?
•	The player should feel encouraged to work towards the Nâfarat decision.
### The missions:
•	Dune Sea
•	Mahûd (not available)
•	Nâfarat
•	Rây
•	Bellakar
•	Mardrûak
•	Umbar
•	Near Harad

**Comment by JukeJukestar** [comment]
Would be nice to have a quick rundown of what is supposed to happen after each mission/ what special mechanics there are supposed to be so I know what to look for while testing.

Currently you utilize conquest and holy war CBs to get the titles you need, are there supposed to be any special CBs?

Do you also get the empire of Abrakhan if you sujburgate the Dune Sea instead of Nafarat first? Since taking over the dune sea is such a huge undertaking, it should probably only unlock after you've subjurgated Nafarat and become an Empire.

The subjurgate Nafarat decision works as intended, becoming your tributary state (Havent tested what happens if the Terror of Nafarat is dead though)
However, the next obvious goal would be to conquer Ray, but this looks odd on the map as your empire is now split in two parts with the Nafarati as a tributary state in the middle.
Does the Ray Empire also become your tributary state or does it stay part of Abrakhan proper?


Two more things I noticed that are probably not intended:

- Abrakhan does not currently get any of their special MAA. This applies to both the Nazgul and his vassals, as they start without the required innovation.
- All of the buildings in Abrakhan are inactive, because you and your vassals have to use orc buildings instead of regular ones, requiring you to spend huge amounts of cash on worse buildings than the existing ones. (this also heavily limits your ability to build up MAA and be aggressive)

**Comment by Remerod** [comment]
I mainly tested some stuff using console commands to answer some of these question of what i "a tester" think is logical. I do agree with some stuff Juke have pointed out but i think dealing with the **To look out for:** would solve much for Abrakhan as a playable tag.

> • Do the missions make sense to the player? Such as, once you’ve conquered the Dune Sea, a couple of other missions open.

I think they do, they it gives off the feel like your taking care off the south. Of course i would maybe want more text flavor to them. But that can wait for later. As they stand for as now i think they make sense in a "basic" way.
Both **Subjugation: Dune Sea** & **Subjugation: Nâfarat** gives you the empire title, and that should be explained in the decision effects in my opinion.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150872202-3a17bd9f-9af4-48c9-8e30-2c7bd7f7c190.png)
The effects/results should be written here.

![image](https://user-images.githubusercontent.com/79544635/150879216-910a7748-9f19-4d9f-822f-cdb01cabff52.png)
Maybe when securing all the missions/decisions there could be an Event like "we have secured the South for our Master, the Lord of the Rings!" Telling the player you "finished" the missions, giving a sense of accomplishment, which i personally like.
 
</details>

> • Are the rewards worth the time and fair?

The rewards could be better in my opinion, they are not that strong, bug good enouth. There could be some narrative event flavors added but not required as a base product(example: we've conquered bellakar muahhaha-text), because text/narrative events are good rewards in themselves but that could be added on in latter patches.
I've added some more stuff in detail below:
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150872368-bfcb21bc-b787-466d-abd7-dde8d52cc5c9.png)
![image](https://user-images.githubusercontent.com/79544635/150872471-27f674d5-a5ae-4752-a64b-e900afadbd2a.png)
I feel like the **Subjugation: Dune Sea** modifer is a good reward, but that it should maybe either give some more men or some other reward, it is an whole de jure empire you conquer after all.

![image](https://user-images.githubusercontent.com/79544635/150874025-025e3089-f588-4288-a480-988c9a99f46d.png)
I feel 300 might be a small number for **Subjugation: Ray** with conquering an whole de jure empire region and all. Should specify what kind of men these are in the Effects.

![image](https://user-images.githubusercontent.com/79544635/150877686-d87f727e-ae50-4182-9f44-fb6c952b6c58.png)
again with **Subjugation: Bellakar**, the army gain seem small, and don't specify what kind of army it is.

![image](https://user-images.githubusercontent.com/79544635/150878238-5c0430a6-5131-479d-a352-993877dae3f7.png)
**Subjugation: Near Harad** a bit weak, need to specify what men, and possible more?

![image](https://user-images.githubusercontent.com/79544635/150878937-dd59ff6f-adb6-4f5e-b9bb-2ea982b7eec1.png)
**Subjugation: Umbar** same as above really.

</details>

> • The player should feel encouraged to work towards the Nâfarat decision.

I think the starting events pushes the player in the right direction, of course there's gonna be people who do their own think, but i think the starting event is more then decent to show the player the natural course to go.
> • What time frame do you estimate Abrakhân completing all the missions minus Umbar and Near Harad in the hands of a competent player?

I've haven't had time to "fully" test it yet, with Abrakhan gone threw many reworks with cb's and other bugs. I doubt it's doable withing 50 years with their cb's for a normal player though. but i can be wrong. 
I do think their is importance to test this though.

**Conclusion:**
There is many think currently Abrakhan lacks flavourwise, like nafarati are the only tributary-made events when there definitely more that can be done for other relams, and such. But i do think that if the **To look out for:** questions are sorted out in a good fashion and some bugs worked out for Abrakhan, they will be ready for an enjoyable for the 2.2 release

**Comment by Remerod** [comment]
I think that more stuff can be added for Abrakhan, but does it need to? if more stuff is added it should maybe tie into the [War in the South](https://github.com/MattTheLegoman/RealmsInExile/issues/291) but as testing goes i think there not much more to test here.

**Comment by jj248** [comment]
Sounds good - I imagine @MattTheLegoman will continue to refine his work in Abrakhan over time, but for now, happy to close this issue.
