### ISSUE TITLE
Additional wonder buildings for new areas

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#225]

**Comment by VectorMaximus** [comment]
Large amounts of new wonders have been added to the new areas. Ready for testing for balance.

**Comment by Remerod** [comment]
Would be nice of a list of them, so no one gets forgotten.

**Comment by VectorMaximus** [comment]
I believe this should be most, if not all of them, in the new southern areas:
- Beacon of Sornomar (Narik-Zadan, Mardruak)
- Arch of Ciryandur (Hazaj-Tollin, Felaya)
- Monestary of Urud an-Khibil (Urud an-Khibil, Felaya)
- Pillar of Urezayaneth (Urezayan, Bellakar)
- Great Haven of Korlea (Korlea, Bellakar)
- Rophazan Mines (Damamar, barony of Koyren, Bellakar)
- Nilulonde (Nilulonde, Bellakar)
- High Shrine of Îshtra (Bur Esmer, Bellakar)
- Temple-city of Pred (Pred, Suza Sumar)
- The Bozisha-Dar (Bozisha-Dar, Ray)
- Citadel of Katri (Tresti, Ray)
- Abaraglareth (Khorsaj, Tulwang)
- Silverine Lighthouse (Adunazain, An-Balkumagan)
- Marath Kharadune (Zadan an-Adun, An-Balkumagan)
- Abrakhan Palace Complex (Abrakhan)
- Souk of Mazharath (Mazharath, Dune Sea)

**Comment by Remerod** [comment]
I took a look at these, and while i'm far from the most cunning person when it comes to balancing number modifiers, I still had some opinions of one or ,ore improvements. I also took a screenshot of all (I think) so others don't have to go into the game and check.

**Beacon of Sornmar** seems fine to me (if not almost a little weak). since it's sailor flavored maybe also give it something with income? nothing to much though, maybe just some taxes?
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150622940-6e6a2539-571b-4882-a65a-b574c6756f5e.png)

</details>

**Arch of Ciryandur** not strong at all. :P  nice lore though. compared to every ones else modifiers, i think this is the weakest one.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150622989-c3663803-9732-4f45-9c68-67f1034fe66a.png)

</details>

**Monestary of Urud an-Khibil** maybe it's a little strong? are the monestary supposed to be outside the temple barony or not? i think it's fine though since it's the seat of the "papacy"/theological realm of Batân an-Inzindi.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150623031-c49b41b1-d3bc-4e0b-8605-f50516c305c6.png)

</details>

**Pillar of Urezayaneth** seems fine, maybe a little weak maybe? 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150623041-24c94a2d-6148-4eff-92ab-d4e7dcacc346.png)

</details>

**Great Haven of Korlea** compared to the others above, it's strong. I think it's fine though
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150621734-02b3e30c-2ba4-449d-99b3-59ce3df6c12a.png)

</details>

**Rophazan Mines** seems fine to me
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150621906-bbfd10f9-6b74-45d4-9b0a-aefc1ce55fa5.png)

</details>

**Nilulonde** i dunno, i think it's fine, maybe a little strong at the last stage. 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150621938-5b4fd3e4-ce2e-4e2f-b157-5bc2f9c79b37.png)

![image](https://user-images.githubusercontent.com/79544635/150621947-02d10495-eaa3-46ec-87de-61b13a330c68.png)

![image](https://user-images.githubusercontent.com/79544635/150621955-322adc1e-cd9b-435f-bbd6-84e1377e275e.png)

</details>

**High Shrine of Îshtra** why the tax modifier? i think the piety plus could be bumped up. Also should this special works building work for everyone or be bound by certain religions? (assuming it don't have that).
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150622071-52c1d67d-cfcc-4fbc-a219-7a509f35006f.png)

</details>

**Temple-city of Pred** I dunno. I think this is fine
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150622140-b112a22c-5e40-4139-a47f-e3d660645349.png)

![image](https://user-images.githubusercontent.com/79544635/150622148-edb07146-1dbe-42a6-9303-fe2af3b839f5.png)

![image](https://user-images.githubusercontent.com/79544635/150622152-c60ebd0d-0582-4d9a-8a71-d8a25f564a29.png)

</details>

**The Bozisha-Dar** maybe nerf the stage one +5 gold/month to +2.5 or something and maybe buff some to taxes instead? I think it's a bit strong. But i would say i think that this special building would be worthy of 3 stages, since Ray is an important region and all.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150622228-b73575c4-8a37-47cf-a1a1-acde749e5e3f.png)

![image](https://user-images.githubusercontent.com/79544635/150622258-3431d230-c0fc-4888-ac78-12fab52cbfbe.png)

</details>

**Citadel of Katri** this one have a lot of modifiers, but i don't see what justify them having a +5gold/month modifer, if they need to have it nerf it to +2.5 or make it about taxes instead maybe? 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150622369-9ea4f642-5ef4-4453-893a-028e82cf29ca.png)

</details>

**Abaraglareth** Honestly, we've spoken on the discord that these modifiers being to strong. But i can see them having all these, but not one stage one! if we added 3-5 stages it could be for the last stage, thus would give the storm marshal a good reason to throw money at something to.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150622448-88e63ae1-3ad9-4841-9457-b3b654950bfc.png)

</details>

**Silverine Lighthouse** i think these are justified, as i assume it connects to the harbor city.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150622538-9a6803aa-3d21-4bc8-90a3-297a0cec64b8.png)

</details>

**Marath Kharadune** i think these are fine, but i would honestly suggest that the red citadel being a last third stage with a new secound pstage having the current modifiers with the 3d one having more/better ones. 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150622598-e4ac3977-56c6-41bc-98b1-9902c1b28cf5.png)

![image](https://user-images.githubusercontent.com/79544635/150622610-c09910fd-8ef1-4e1d-9f11-4a0a7990510f.png)

</details>

**Abrakhan Palace Complex** maybe there is a little bit to much dread with the combinations of stage 2 & 3? I think also it would be nice of their being a disrepair stage, just like Marath Kharadune have. it can still start at Palace Complex: Gate Pools but i assume that the Golden King repaired his palace when he returned and would nice to represent this. + i dunno if you can destroy special works but maybe we had something like that in the future? i think i overthinking this now :P
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150622774-d1b738c8-9d44-4dc5-96d9-94a10e3defd4.png)

![image](https://user-images.githubusercontent.com/79544635/150622777-f3caa3d8-47b8-4178-8da1-6f1a5d711f40.png)

![image](https://user-images.githubusercontent.com/79544635/150622785-2bda451e-f6d8-414e-a1f4-3219c5b08319.png)

</details>

**Souk of Mazharath** I think this is fine, maybe even could get a small +gold/month modifier. but i think deviding it up into 1-3 stages instead of just one would be more fun and cooler for the player.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150622878-b7c6804e-9d4d-4ed7-b48d-7289cd0f619f.png)

</details>

**Coves of Irtîl** seems fine to me.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150622744-ebfbbb02-e8d8-47ae-8141-97473ecba842.png)

</details>

Overall i think most are fine, some are a bit weak and very few are to strong, in my opinion, but with the exceptions of the pillars/lighthouses i think that some of the special buildings that don't already have it could have some more stages to them, it is after all a little bit fun to upgrade your stuff, and if places like Pred have em, i don't se why Abaraglareth couldn't.

**Comment by Remerod** [comment]
Redarkady pointed out we missed some, and i remembered that we missed Nykkea. So making a updating comment.

**Shipyards of Nykkea** seems fine, I like the embarkation reduction.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150634804-3a2c3ab8-2c90-4a7e-a7d6-117384f0e6ae.png)

</details>

**Citadel of Hyarmendacil (Dusalan)** I think this is a bit boring of a modifer, i think more could be done, have the first stage being "ruinous"/"disrepair" just like Marath Kharadune, and have at least one more stage(or make it 3 staged) that repairs the citadel. Either way i think it has a lot more potential then it is now.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150634886-987f8c95-96db-40a6-b82c-115f586f29e3.png)

</details>

**Retreat of the Kings (Bar Morthil)** current modifiers seems fine to me.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150634981-8a49eb4f-a0a1-4e90-a0f4-f20f5a1ab45c.png)

</details>

**Walls of Linhir (Linhir)** if these are "Numenorean walls, i think it could be reasoned that they deserve more then +1 in fort level. Maybe something between 2-5 ?
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/150635203-f27e3f85-2d11-4e5b-b347-2769987fa846.png)

</details>

**Comment by Remerod** [comment]
Jamie linked a very good webpage to take into account when giving special buildings modifiers, and this is something to take into account when doing em/balancing them. So gonna repost it here so it won't get lost in the discord! 

https://ck3.paradoxwikis.com/Special_buildings#Historical_buildings

**Comment by VectorMaximus** [comment]
Made tweaks to most wonders.

Only ones without changes (well, ones that people had commented on):
Abaraglareth - as a 'Masterwork' of An-Balkumagan that cannot be replicated in the modern age, makes sense to only have a single level to me
Bozisha-dar - don't have any good ideas for additional tiers, but am open to suggestions. Did tweak the tier stats slightly.
Citadel of Katri - for the reason Juke raised, leaving it as is. Gives the 'Traditionalist' vassal a powerbase to work with

**Comment by Remerod** [comment]
I think we all have agreed that most of these are fined, we have had no complaints either, and could easily be changed in the future if a certain nation gets unbalanced with some of them. So i'm closing this for now
