### ISSUE TITLE
Review 'Destroy Mordor' religious conversions for all areas

### ISSUE THREAD

**Issue by Jermanlordy** [MattTheLegoman/RealmsInExile#235]
After Mordor is destroyed thru descision Saruman converts to Mulkheri even though it would make more sense for this to be The White Hand Cult

**Comment by jj248** [comment]
See above issue re: Golden King when reviewing.

**Comment by JukeJukestar** [comment]
Ithilien Lidless eye counties usually stay lidless eye
Ive also seen some counties in Nirn survive, but I think having a few should be fine ot represent the few surviving sauron cultist holdouts that slowly get destroyed/ converted

**Comment by jj248** [comment]
@JukeJukestar - Is this on the latest version or an anecdote from the past? As I recently updated the logic for this maybe a few days ago.

**Comment by JukeJukestar** [comment]
@jj248  
This was last week when I did my Cassimiri Gondor playthrough and defeated sauron

**Comment by jj248** [comment]
Best to test on the latest version then as that'll be pre fixes.

**Comment by JukeJukestar** [comment]
so did some testing: where I went around the world as sauron and converted a bunch of realms to 100% lidless eye, before destroying mordor

- abrakhani often convert to kanra, but also sometimes to sanbaizani instead (?) especially the western vassals in darsalan

- black vizier converts to morgoth cultist as his culture does (his counties still convert to kanra)

- stormhost convcerts to morgoth cultists instead of their own dark religion

- ray converts to morgoth cultist instead of their dark solar religion

- Tedjin convert to morgoth cultist instead of their native evil religion

- people around the dune sea convert into sanbaizani as its a native dark religion for their culture group

- the mouth and his orc counties convert to kingsmen if he still holds the duchy of barad dur, the county of barad dur is given to a random shakhburzdai uruk (I actually think that maybe the mouth should stay lidless eye as a sort of "post sauron remnant" to be annihilated soon

- county of thaurband converts to shakhburzdagi and is held by orc count instead of native nurniag
-

**Comment by Remerod** [comment]
> the mouth and his orc counties convert to kingsmen if he still holds the duchy of barad dur, the county of barad dur is given to a random shakhburzdai uruk (I actually think that maybe the mouth should stay lidless eye as a sort of "post sauron remnant" to be annihilated soon

maybe The Mouth would go into hiding(if alive & ai) and help forming something like the _Cult of Herumor_  or the **Black Cartel **

_but this might be feature creeping as of 2.2_

Sources:
https://notionclubarchives.fandom.com/wiki/Cult_of_Herumor 
https://notionclubarchives.fandom.com/wiki/Black_Cartel

**Comment by JukeJukestar** [comment]
After the religious update in abrakhan:
cult of zigur is not destroyed, its only replaced by kanra in counties personally held by the golden king at the time of his death

**Comment by Remerod** [comment]
> After the religious update in abrakhan:
cult of zigur is not destroyed, its only replaced by kanra in counties personally held by the golden king at the time of his death

is this the only thing left to be fixed? or are there other stuff left that's need testing on this issue?

**Comment by Remerod** [comment]
it's fine apparently, closing this
