### ISSUE TITLE
Cult of the White Hand Overhaul

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#362]
Most players wont even know they have to manually convert to the white hand, it should be event based like the conversion to Lidless Eye.

The Cult of the White Hand also has some strange choices for doctrines and tenets.

<details>
<summary>The White Hand as it stands</summary>

<img width="598" alt="saru1" src="https://user-images.githubusercontent.com/76008882/160275863-18bc63ee-abd6-41d6-8559-0a043ccbf529.PNG">

<img width="607" alt="saru2" src="https://user-images.githubusercontent.com/76008882/160275866-5c80db63-8132-41c8-b860-97a79fec6337.PNG">

</details>

# 
Tenets

Literallism fits Saruman well I think, as he thinks of himself as being incredibly wise and he would definitely take pleasure in theologically rap battling those he considers his inferiors

Inner journey sort of works, but I would personally see "The Encroaching Shadow" as a far better fit as it not only makes Sarumans ambition into a virtue (which makes sense since this religion was basically made by himself to make everyone see how great he is) but also because it makes him more aggressive.

Hedonistic doesn't fit Sarumans lifestyle very well I think because while he is known to enjoy some pipeweed every once in a while, he never struck me as a glutton or someone looking to become one.
Instead, I think it would be great if Saruman got a custom "Subjugation beneath the Orthanc Tower" tenet, which would mirror Saurons "Subjugation beneath the Dark Tower" tenet (also referencing "The Two Towers" and the dualism between Sauron and his offbrand enemy Saruman) Perhaps this tenet could make either just or arrogant a virtue instead of greedy, so saruman is further exhaltified.

# 
Doctrines

I would think that monogamous would fit Saruman better than polygamous.

Bastards could be set to No Legitimization, as this is a relatively rare doctrine and would sort of fit well.

Other than that I find it very odd that there is no religious head. Shouldnt Saruman be the temporal religious head? The title could be called "The White Council" and could be either duchy or kingdom tier (although it would be weird for isengard to have the religious title as the primary one so maybe duchy tier)

**Comment by VectorMaximus** [comment]
Generally speaking, my thoughts - 
The doctrine changes suggested make sense to me. We've already reworked it a little to have a Head of Faith title, so that's good.

Saruman will convert to the White Hand via event if he decides to go against Sauron after conquering Rohan. 

For the tenets - Encroaching Shadow seems a bit too 'overtly evil' for what this religion is supposed to be portraying itself as. The religion, in and of itself, is not the source of belligerent expansion. Saruman at least is *billing* this as a kind of 'oh I'm just so wise and benevolent everybody should listen to me, I know what's best!'. Instead of 'Inner Journey', I can instead see Esotericism or Religious Law as fitting in that slot.

For the 'Subjugation beneath the Dark Tower' equivalent, I agree it makes a nice parallel, but I'd tweak it significantly, so here's what I'd recommend:
"Supremacy of the White Wizard"
_The White Wizard in his infinite wisdom and benevolence has sought to guide us in our conduct. He is the final arbiter and judge of our actions and our failings._
- Enables the head of faith to excommunicate, grant indulgences, etc
- Increases taxes in provinces of the true faith (tithes, basically)
