### ISSUE TITLE
Rhun / Easterling Men at Arms Suggestions Board

### ISSUE THREAD

**Issue by AxiosXiphos** [MattTheLegoman/RealmsInExile#402]
### **Rhun Men At Arms Suggestions Overview**

Just wanted to type up some of the discussion we had today regarding Rhun MaA. After speaking to Vector & Rémerod it looks like we are currently looking at 3 Generic Rhun MaA, and then 2+ unique ones for the various Realms. 

Current thinking for Rhun MaA are;

- Pikemen
- Cavalry (Kataphracks)
- Macemen or Swordsmen
- Elite Cavalry For Golden Horde (Loke-Innas Rim)
- Igathic MaA (Chariot/Wainrider?)

### **Sources**

Tolkien was fairly light on the detail when it came to the Rhun armed forces. We have mention of the Wainrider Chariots of course and 'Swarthy Bearded Men with Axes' though it is dubious whether this was Rhun, Khand or some other forces of Sauron. As such our primary source will be the Weta designs + any community designs we can take inspiration from.

**Movie / WETA**
<details>
Everyone of course remembers the black gate marching scene; where we see Rhun Halberd/Pikemen;

![image](https://user-images.githubusercontent.com/92896163/162799647-6ba48516-41a9-42d6-b9d6-32bef3247180.png)

Rhun soldiers also took part in the battle of Pelennor fields and were present in the movies (though blink and you will miss them);

![image](https://user-images.githubusercontent.com/92896163/162799869-7bd18e1b-0315-4114-ab0f-42edd5a0eeb2.png)

The same design with the same weapon. This appears to be our 'standard' soldier of the Golden Horde / Rhun
</details>

**Third Age Total War**
<details>
Third age (and Dawnless Days) have their own Rhun unit nomenclature. Focussing on a naming convention using 'Loke-X Rim'. This was pointed out to obviously be tangibly related to the Golden Hordes Loke-Khan specifically; so while it may be useful; is not something to be used for generic Rhun units. The third age Rhun units can be found here;

https://www.honga.net/totalwar/faction_units.php?v=third_age&f2=rhun

What is useful though are the images and overall unit designs.
</details>

**Games Workshop**
<details>
GW have a full 'Easterling' range for their wargame. The range is fairly tight and can be broken down into the following;

Easterling Warriors With Swords/Pikes/Bows;

![image](https://user-images.githubusercontent.com/92896163/162802702-912e2a08-b646-40ea-9493-24ea9ca0d8c8.png)

Black Dragon Warriors With Swords/Pikes

![image](https://user-images.githubusercontent.com/92896163/162802785-e6d43ac1-6762-4fa0-975e-5f5e9f599c01.png)

Black Dragon Acolytes Twin Swords

![image](https://user-images.githubusercontent.com/92896163/162802864-265928e8-d9ce-4f64-94cf-31bdfe5c9a06.png)

Easterling Kataphracts with Swords

![image](https://user-images.githubusercontent.com/92896163/162802928-cae862ed-e32e-4daf-be5d-b85d9189cd56.png)
</details>

### **Unit Suggestions**

Below are a complied list of the MaA as I believe they stand with our thoughts;

**Pikemen**
<details>

These are fairly straight forward. The only Rhunnic soldiers we see in the movie are Pikemen, Both GW & Total War Third Age put an emphasis on the Pikemen in their game. Seems to be a requirement.

Naming Options: Loke-Gamp Rim (Golden Horde), Rhun Pikemen / Rhun Phalanx

![image](https://user-images.githubusercontent.com/92896163/162815680-10833f89-e2d1-482d-86a5-66d709d3d487.png)

Third Age Lore Snippet: Quite literally the bite of the Lôke-Khans army, the Lôke-Gamp Rim are highly trained pikemen and swordsmen. Wielding nine foot pike and halberd hybrids, they are the infantry which will ensure that the men of Rhun are never defeated by the horses of Rohan again. Their job in battle is to close with the enemy under the protection of the Dragon's Fire and pin them in position, making the enemy susceptible to envelopment and destruction. They rely heavily on their pikes to provide the protection they need, keeping the enemy at a distance, and are therefore not as heavily armored as the other infantry in the Lôke-Khans army.

Stats Sources: Should mirror the base Pikemen MaA in many respects; however as these are also the Standard Rhunnic troops they should also emulate Gondor Soldiers in terms of quality.

![image](https://user-images.githubusercontent.com/92896163/162819282-d686f4d5-35e3-41f1-9e43-cc8e990f7c09.png)
![image](https://user-images.githubusercontent.com/92896163/162819503-8c4e414c-57e0-44bf-9d3d-dc8a095d8214.png)
_Note these are effected by domain advantages._

Suggested Stat Block:

Damage: 
Toughness:
Pursuit:
Screen:
Type:
Counter Types: Light Cavalry, Heavy Cavalry, Camel Cavalry, Elephant Cavalry
Terrain Effects:

Description:

</details>

**Macemen**
<details>

We need another infantry unit for Rhun. Anti-infantry mace men would work as a nice foil to the Pike unit while keeping a distinct flavour. Once again we could lean on Third Age Total War;

Naming Options: Loke-Flag Rim (Golden Horde), Rhun Heavy Infantry / Rhun Shock Troops

![image](https://user-images.githubusercontent.com/92896163/162817131-7985681c-c865-4504-b87e-61c8439a8146.png)

Third Age Lore Snippet: Heavily armored and armed, the Lôke-Flag Rim are capable shock troops that are incredibly effective against armor. They wield heavy steel maces and axes and protect themselves with large shields. Primarily, their role is to protect the flanks of the Dragons Teeth, but they can also be used to soften the enemy up prior to main battle line engaging in melee. Of all the regiments the Dragon’s Skin is the most versatile, being capable of storming citadels or fighting on open battle plains. Used correctly they are nearly an unstoppable force.

Stats: TBC

Suggested Stat Block:

Damage:
Toughness:
Pursuit:
Screen:
Type:
Counter Types:
Terrain Effects:

Description:
</details>

**Kataphrakts**
<details>

Cavalry are an important part of a Rhun force. Both GW & Total war suggest heavy shock cavalry (clearly inspired by Byzantine cataphracts).

Naming Options: Rhun Kataphrakts

![image](https://user-images.githubusercontent.com/92896163/162818291-2ef5129a-11ab-4a31-9ec0-6ce5d3dce949.png)

Third Age Lore Snipper: Does not exist; only for the full Loke-Innas Rim

Suggested Stat Block:

Damage:
Toughness:
Pursuit:
Screen:
Type:
Counter Types:
Terrain Effects:

Description:

</details>

**Loke-Innas Rim**
<details>

Elite heavy cavalry for the Loke-Khan.

Naming Options: Loke-Innas Rim

![image](https://user-images.githubusercontent.com/92896163/162818291-2ef5129a-11ab-4a31-9ec0-6ce5d3dce949.png)

Third Age Lore Snipper: Foremost among the Lôke-Rim are the Lôke-Innas Rim, the heavy cavalry of the Khan and the finest cavalry in all of middle earth. Clad in golden steel plate armor, scale armor, and steel chainmail, all the while mounted upon massive war horses draped in armor, the Kataphracts are an imposing force on the battlefield. They charge into battle with long cavalry spears and carry with them menacing curved sabers. Their presence on the battlefield gives incredible strength to the Lôke-Khans army and hence provides the Will of the Dragon Regiments. While capable of frontal assaults, the Dragons Will is best utilized in concert with the other regiments. They provide the final envelopment of the enemy and the final devastating charge into their rear. Select squadrons of kataphracts also form the personal bodyguard of the Lôke-Khan and his Generals.

Suggested Stat Block:

Damage:
Toughness:
Pursuit:
Screen:
Type:
Counter Types:
Terrain Effects:

Description:

</details>

**Comment by Remerod** [comment]
# Suggestions from LOTR Rise to War
In the mobile game they have around 5 really good, as in easterling flavored- units.

**Pikemen** 
"Pikemen are battle-hardened and disciplined skirmishers." I think at least this imagery make for a cheap unit or maybe an one for older times? Could name them Easterling Pikemen. 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162968178-e807f377-fea4-4d0c-86f1-2aab472b6eef.png)

</details>

**Marauder** 
"Marauders make their living terrorizing the undefended villages of the free folk." I like the picture and flavour, they feel like warbands rather then standardized soldiers here. same thoughts on these as Pikemen. 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162968618-c058133f-582d-4153-a455-40fbbf969811.png)

</details>

**Halbardier**
"Halbardiers are the bane of the free folks mounted riders. Their long polearms make enemy cavalry rushes highly costly." we all know we gonna have some form of this unit, I'm mainly posting this one here because i like them to be named Halbardier something, since we already have a standard pikemen in ck3, it could be good to have a different name, Plus Halbadiers are way cooler.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162969170-6b824537-f13e-4f8f-8284-c705b86ef254.png)

</details>

**Dragoon** 
"Dragoons make up the vanguard of Easterling armies". I'm with everyone that Kataphrakts is a better name, but i do like these as an alternative (as dragons and stuff is also important in easterling myth) and if nothing else maybe the flavor-text could be reused. 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162969600-88bea042-0287-4d3e-8099-756fac660472.png)

</details>

**War Chariot** 
"The wheels of the War Chariot are at just the right height for their mounted scythes to slaughter unsuspecting enemy infantry or cavalry". I think most is on board of having some kind of war chariot. I like the image of this one, and the flavor text
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162970041-aba40175-6e0b-4506-a672-7d1199a763f5.png)

</details>

**Summary:** I feel like these are very generic, but that is also a god thing? and as i said on most of them, there is some good and short flavor texts for them

# Rise of Mordor/The Dawnless Days
A great total war lotr mod and one that we have some collaberation with. They also have some great units for the Easterlings.

**Clan Axemen**
Basic infrantry unit, if nothing else maybe good tribal unit?
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162973411-32ccedce-0f76-4b38-8804-1afdf35172ae.png)

</details>

**Rhûnic Warriors**
Maybe a good upgrade from the Clan Axemen?
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162973650-4956949b-cc70-4f91-8473-a8487b33d8b4.png)

</details>

**Lókë-Rim Macemen**
Good MaA for a heavy unit maybe? 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162973931-2984dd5f-3037-4e8d-915a-2aac6db67463.png)

</details>

**Rhûnic Savages**
These troop feels very "easterlings of old" maybe some that have not gone into the more modern times? maybe we could give them to a specific culture? 
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162974341-29096ea9-653b-4225-937e-f6d280e27aa3.png)

</details>

**Clan Spearmen**
again, maybe a good tribal MaA?
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162974159-cb3c0a53-968a-465c-a586-69595f841fd9.png)

</details>

**Clan Guards**
feel like a good standard spearmen troop, but maybe a good name?
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162974600-9015b37e-3eb2-4274-9b87-ae7b40be18d7.png)

</details>

**Lókë-Rim Halbardiers**
Just like lotr rise to war, these are called Halberdiers, i really think one of the elite infantry should be "inspired" by these.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162974989-a2d5f310-4d83-4286-abe6-4e839bf61ee7.png)

</details>

**Clan Huntsmen**
good tribal archer unit?
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162975255-8dc9cefc-352b-4760-a956-46c56d29f191.png)

</details>

**Rhûnic Archers**
Good name/feel for archer unit maybe? or maybe to standard.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162975417-e263d1f8-c404-4079-9b19-82bc293ea908.png)

</details>

**Lókë-Rim Archers**
Elite Archers?
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162975699-7f712c2d-84d8-495a-ae67-eafb1a2ed848.png)

</details>

**Clan Raiders** 
good tribal light infantry?
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162975858-2f2a131a-3d99-494c-8905-843dfbc495d8.png)

</details>

**Warlords of Rhûn** 
these feel like a weird combo between tribal and civilized to me, they don't have the traditional gold of the civilized one, but maybe these could be a more holy warrior revering the dragons or something?
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/162976031-ca5ffd93-87fd-48f7-8830-1bc985b5173a.png)

</details>

**Summary:** 
if nothing else i feel like Rise of Mordor/The Dawnless Days have a loot of good tribal feel to their units, and i assume we would need some of that also.

**Comment by Remerod** [comment]
The rhûn and gotten MAA, and while i think they've gotten enough stuff for a release, i want to keep this open a while longer, in the case i or someone else want to add something special to them. 

So i'll move this to work in progress for now

**Comment by jj248** [comment]
Closing and linking to #201 for reference during that chunk of work as this is not in progress.
