### ISSUE TITLE
Investigation "Abnormal Winter" sorcery modifer

### ISSUE THREAD

**Issue by Remerod** [MattTheLegoman/RealmsInExile#411]
it's been brought up that maybe the **"Abnormal Winter" sorcery modifier** maybe need to be nerfed. 

we should overview this, test it out and see "if" it's to OP

**Comment by josejuanmartinez** [comment]
Abnormal Winter and Cast the Darkness definitely need to be nerfed. If you cast it as Sauron, you get like hundreds of counties and characters with strong debuffs.

**Comment by JukeJukestar** [comment]
Still incredibly OP, but sorcery is also still WIP.

**Comment by JukeJukestar** [comment]
Moving this over to non release critical.
For those unaware of how the spell works - Its a mighty powerful spell so strong only sauron can use it. It adds a modifier to all counties of hostile neighbouring kingdoms (unsure if its based on religion, who youre at war with, or something else) that reduced supply limit in those counties all the way down to 1.000 - effectively ensuring that anyone in those lands will starve their armies to death, and also makes armies incredibly slow. The modifier lasts a few years and Ive seen Sauron use it a few times.

Quick fix would be to reduce its effects to maybe 50% supply instead of 100%?

**Comment by jj248** [comment]
Adjustment made to the modifier in line with Juke's suggestion.  Seems like a pragmatic solution.

Pushing to testing for feedback on new value.

**Comment by JukeJukestar** [comment]
Seems to be working - its hard to test the modifier right now since sorcery is broken. closing
