### ISSUE TITLE
Bug: Boromir has +7 martial from the horn of gondor because of a leftover modifier

### ISSUE THREAD

**Issue by JukeJukestar** [MattTheLegoman/RealmsInExile#487]
![image](https://user-images.githubusercontent.com/76008882/186926678-37ed0f64-faf1-4db9-8142-a52ac2409073.png)

This is Boromir.

![image](https://user-images.githubusercontent.com/76008882/186926876-80b0e417-4815-4a7c-ac3e-3971ebe0323f.png)

This is Boromir 1 day into the game.

# What is happening?

![image](https://user-images.githubusercontent.com/76008882/186927029-531acb61-6b6b-49ff-b651-5140e3fa6e6f.png)

Boromir has the Horn of Gondor as an artifact. Pretty cool, decently balanced and very powerful.

![image](https://user-images.githubusercontent.com/76008882/186927108-e03fbd64-b27d-412e-b610-6b7df140f574.png)

However, he also has this modifier which i can only assume is a leftover from when we didnt have artifacts.
+5 martial is insane! This modifier should be removed. 17 Martial would fit Boromir much better as a very competent commander that is not a god.

# Side note

![image](https://user-images.githubusercontent.com/76008882/186927482-64ed8546-c75e-4bfb-82a9-a15354c2a19c.png)

Faramir is actually very bad statwise, despite him probably being a better ruler than Boromir. Perhaps his martial could be nerfed and he could isntead get decent base stats in everything else as well as a positive lvl 1 intellect trait?

**Comment by RoughlyTheSizeOfAMOROOON** [comment]
JukeJukestar was later found dead, stabbed twenty eight times by what the police are calling a 'Horn-shaped Weapon'. Boromir insists he had nothing to do with it, and in an unrelated note that his 'martial is completely fine, don't worry about it'.

More seriously, that does just seem like a small bug. As for Faramir, I dunno. He already has a inheritable trait AND Strong blood. Maybe just a stat increase all around instead of getting intellect_good_1

**Comment by jj248** [comment]
Done and consulted with Vector - back to @JukeJukestar for feedback.

**Comment by JukeJukestar** [comment]
Works.
