### ISSUE TITLE
Review and balance costs and cooldowns of colonisation

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#523]
Current view is that colonisation progresses too quickly.

**Comment by jj248** [comment]
Going to pick this up as the next piece of work.

**Comment by jj248** [comment]
This should largely be done now, save for the gui work that needs to be done to show the true colonisation cost.  Modifiers of blocker buildings are largely placeholder, so any input from testers on these is welcome.

Note that there are outstanding content updates for #518 and #519 that is separate from this.  This really is focused on the framework.  There's also #520 to add more variety to blocker types we can use.

**Comment by jj248** [comment]
Breakdown and true cost now shown.  Moving this to testing - feedback particularly welcome on balance / costs and the system framework in general.  Let's leave feedback on the specific content of #518, #519, and #520 to be covered in those specific issues.

**Comment by Jauffr** [comment]
From both observer games and testing for myself I find that colonization costs and speed are working well where they are at right now. It typically takes a very long time for the AI to colonize central Rhovanion and even longer to deal with the drakes north of Murkwood. It definitely feels like the AI is very cautious when deciding to actively colonize. Often leading to situations where not even a single county has begun to be colonized until Lasgalen begins 7 or so years in. A determined player can work around this however. If you save your money and focus a good steward on the task, players (Especially Dale and Lasgalen due to their excellent stewards) can finish colonizing a county just as fast as a new one is able to begin. This requires their entire economic power to be focused on it however and will never be done by the AI. For the AI to completely colonize the difficult terrain, you will be waiting a good century and still likely have a couple counties in Dagorlad, or at least one drake county that dale insists on trying to take on with their lacking prowess until the elves eventually take it, or if Brand lives long enough to take it all himself

There is still rare ocasions where an in progress colony can have an event to create a holding. I am not sure what the source of it would be exactly, nor how much of an issue this actually is. After colonization finishes, it functions like a correct holding.
![Screenshot 2023-02-22 025322](https://user-images.githubusercontent.com/108106660/220585391-6ca7f993-e7e7-459c-a55f-1f5ac755883d.png)
