### ISSUE TITLE
Thranduil's Halls wonder

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#543]

**Comment by RedArkady** [comment]
Good thoughts Juke. No idea whether Matt has a special model planned for this one. I'm minded to think it *should* be super-strong as its a subterranean fastness protected by magic doors, but let's see how it plays. Happy for you to add encyclopaedia links if you think them appropriate! I'm a bit lazy at that and I'm sure Brice is bored of adding them to my stuff and would welcome someone else helping out.

**Comment by Remerod** [comment]
The model has it's own issue https://github.com/MattTheLegoman/RealmsInExile/issues/383
![image](https://user-images.githubusercontent.com/79544635/197186611-be7dbb39-fee8-4d39-9163-6e1d569212c5.png)

I agree that Thranduils halls should be somewhat strong, which is why i don't necessarily think it should be upgradeable, I personally like upgradeable special works but that doesn't mean that all of them needs to be one, and Thranduils hall's is one i don't see being expanded upon because elves like to create "final" products and i always imagined that the Mirkwood elves being more "stagnant". 

I do however agree with Jukes take on the fort, the elves already have very strong forts, plus they get advantage modifiers, maybe buff that and slim down the forts? We should avoid having forts that are 50 to "a bazillion number" strong

But i don't think it's to power, so seeing how it play out is a probably for the best

**Comment by JukeJukestar** [comment]
Closing this for now - the modifier is powerful, but not OP. No upgrades as of now, they are static.
