### ISSUE TITLE
Dorwinion succession mechanics

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#545]
Lock down special succession type for Dorwinion so it cannot be removed from the title except by a decision to convert to primo.

**Comment by jj248** [comment]
Changed removal cost to be very high - need feedback on exactly what @VectorMaximus wanted the conditions for the decision to be.  Some ideas might be:

- Maximum Crown Authority
- Last 3? Rulers all from same Dynasty
- Minimum Court Grandeur Level?
- Income over a certain level?
- Mimimum Renown level?

**Comment by VectorMaximus** [comment]
Broad thoughts:
Maximum Crown Authority
Winelords affiliation (Great Merchants would not crown a king)
Opinion of all powerful vassals above a certain threshold?
Certain prestige level.

I hadn't thought of the 'last 3 rulers of the same dynasty', but it broadly makes sense - its basically codifying de-facto kingship and ending the pretense of election.

**Comment by Jauffr** [comment]
The decision is not functional, however the law is not capable of being removed otherwise. When the decision is taken, it has no effect on the law
![Screenshot 2023-02-23 172325](https://user-images.githubusercontent.com/108106660/221061719-aac816db-2251-46bc-ae8b-eeaec13e26ac.png)
![Screenshot 2023-02-23 172342](https://user-images.githubusercontent.com/108106660/221061721-c8a3c9b5-bce7-4868-8798-e0de1bd7cdd3.png)

**Comment by jj248** [comment]
Tweaked so it should now clear all laws from Dorwinion title.  Moving back to testing @Jauffr .

**Comment by savagesach** [comment]
The decision works as intended, clicking it now removes all succession laws.
![image](https://user-images.githubusercontent.com/86676697/221400490-e7d93ea1-3150-418f-a840-a3177fc27f66.png)
![image](https://user-images.githubusercontent.com/86676697/221400501-ff805a02-f25e-4138-b8ba-5bd1f2919903.png)
