### ISSUE TITLE
Make Sauron head of faith for relevant faiths

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#552]
@VectorMaximus to define which faiths this should be.

**Comment by jj248** [comment]
I'm generally minded not to do this, except for *maybe* the Lidless Eye cult.  Ultimately I think we should come down on the side of whatever makes things most interesting gameplay-wise.  Going to ping @JukeJukestar as he's usually really good at providing input from that angle.

**Comment by JukeJukestar** [comment]
We had a discussion on discord a while ago, see the thread there for more info.

I am personally opposed to this, since Sauron doesnt take on the duties a head of faith would have for those faraway realms - instead he would likely appoint a local theocratic high priest (See Haruzan for example) loyal to him, which I think it better.
I also think it makes sense for the Cult of Zigur to be led by the Golden King instead of Sauron

**Comment by jj248** [comment]
Vector has made all the Mordor faiths have Sauron as head but not for more far-flung faiths.  Moving to testing for feedback.

**Comment by JukeJukestar** [comment]
working as intended far as I can see.
