### ISSUE TITLE
Wildmen invasions can target Wilderness

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#573]
![image](https://user-images.githubusercontent.com/26043074/196925488-fbc573c4-7d4d-41ab-a217-7f024b6f18ca.png)

**Comment by jj248** [comment]
Pinging @MattTheLegoman and @josejuanmartinez on this as the ones who have primarily worked on wildmen invasions and wilderness respectively. :)

**Comment by josejuanmartinez** [comment]
Hey! This happened a couple of months ago, I found parts of the code where the wildmen were being triggered and tried to patch so that if it's a wilderness, it does not trigger it.

It seems it was an unsuccessful attempt :) So anyone knowing all the details of wildermen can take a look, that would be very helpful.

**Comment by jj248** [comment]
I believe @MattTheLegoman pushed a fix for this.  One for testers to look into and keep an eye out for again.

**Comment by Jauffr** [comment]
It has been months and no one has brought this subject up. I have been running a ton of observer games the past few days and have never seen anything like that. And that's with doing extensive testing on colonization and wilderness things in general. Unless anyone has something to post on the subject, I suggest it be closed

**Comment by jj248** [comment]
Good enough for me!  Closing.
