### ISSUE TITLE
Adopt Special Succession Type decision is broken

### ISSUE THREAD

**Issue by savagesach** [MattTheLegoman/RealmsInExile#648]
![image](https://user-images.githubusercontent.com/86676697/217113298-83511f0a-f6c7-4a15-abf9-2886872a5ef6.png)
Taking the decision does not change succession type at all

**Comment by savagesach** [comment]
![image](https://user-images.githubusercontent.com/86676697/217113430-7819b6d6-2296-412e-b1ba-76ba77a21e1b.png)

**Comment by jj248** [comment]
I've investigated this, and it's because we have some Dunlendings eligible to take the decisions and make Thing / Tanistry succession, but those successions are actually disabled.

I can fix this pretty easily, but I think I'll take the opportunity to properly think about which cultures should be eligible to instate Things, Tannistry and Witanagamot; and rebrand them while I'm at it.  Will chat with Vector when he's awake on the lore front.  

For me, the following seems reasonable:

- Tannistry: Available to those of Gwathiurim and Daen heritage.
- Witan: Available to those of Eotheod heritage.
- Things: Available to Northron heritage.

@VectorMaximus ?

**Comment by JukeJukestar** [comment]
Sounds like a good solution, Jamie

**Comment by jj248** [comment]
> I've investigated this, and it's because we have some Dunlendings eligible to take the decisions and make Thing / Tanistry succession, but those successions are actually disabled.
> 
> I can fix this pretty easily, but I think I'll take the opportunity to properly think about which cultures should be eligible to instate Things, Tannistry and Witanagamot; and rebrand them while I'm at it. Will chat with Vector when he's awake on the lore front.
> 
> For me, the following seems reasonable:
> 
> * Tannistry: Available to those of Gwathiurim and Daen heritage.
> * Witan: Available to those of Eotheod heritage.
> * Things: Available to Northron heritage.
> 
> @VectorMaximus ?

![image](https://user-images.githubusercontent.com/26043074/217559491-a3fae209-3627-45e1-aec6-e66f2c15937f.png)

Added - ready to test.  AI cannot take decision. @JukeJukestar

**Comment by savagesach** [comment]
the decision works as intended
![image](https://user-images.githubusercontent.com/86676697/220463875-9a7e10d4-e808-42fc-a176-66f57e7c2dc6.png)
![image](https://user-images.githubusercontent.com/86676697/220463925-2b4c1057-d9ed-4f64-9535-63ae65c2df1f.png)

**Comment by savagesach** [comment]
forgot to show the beornings as well
![image](https://user-images.githubusercontent.com/86676697/220464434-c8189795-913e-42e3-86fe-e3723ee5cce2.png)
![image](https://user-images.githubusercontent.com/86676697/220464476-c6b2b07a-7216-4c10-a39d-eabd9a47d4ea.png)

**Comment by savagesach** [comment]
Eotheod Elective
![image](https://user-images.githubusercontent.com/86676697/220464871-7b58fbe6-a1ea-422e-8fb8-37deb48f653a.png)
![image](https://user-images.githubusercontent.com/86676697/220464976-1a5f2172-7459-4db2-ac82-5a8720c662eb.png)
