### ISSUE TITLE
Domain limit too high

### ISSUE THREAD

**Issue by jj248** [MattTheLegoman/RealmsInExile#684]
I think that domain limits are generally too high in Realms, with a lot of key characters having limits over 10, resulting in massive bloating of power and incomes relative to vassals, reducing some of the challenge of the game.  

This is largely for two reasons:

- We start late in the tech tree, and so we stand to gain up to 4 domain limit from innovations.
- Stat bloat in Realms is real, so characters get more domain from Stewardship than is typical from every 5 stewardship.

To resolve this, I want to experiment with making tweaks to either / both of these effects.  To start the experiment, I'm going to:

- Remove 3 of the 4 domain limit boosts (retaining the one in the final age).
- Double the threshold for Stewardship's bonus to 1 for every 10 stewardship points.

I expect that these changes may push some starting characters over their domain limits.

Pushing this straight to testers for balance feedback.

**Comment by Jauffr** [comment]
I feel that the domain limit is in as good a place as can be expected. Small tribes are capable of holding enough land to become a duke, so long as they don't have less than 7 stewardship (and if they have less, then they deserve the penalty) while powerful independent realms are forced to delegate more power to the vassals. There will always be outliers of course, like Denethor and Bain of Dale. Feel that these characters are not given an excessive advantage however. It more seems that their domain boost from stewardship is exactly what they need to keep pace with the threats around them. In the case of Dorwinion, the minus 1 instead of 2 from master Merchants accurately conveys the intended experience of holding onto a small amount of highly developed counties, while vassals run the rest and politics are your main goal.

**Comment by jj248** [comment]
Agreed - feels like we're in a decent spot.  Anything else can just be scaled by tweaking character stats in history files.  Closing.
