### ISSUE TITLE
Aladegan rework

### ISSUE THREAD

**Issue by RedArkady** [MattTheLegoman/RealmsInExile#741]

**Comment by RedArkady** [comment]
Jamie, as requested making an issue here before it gets pushed back to the testers, as I can't figure out where to define that missing loc.

![image](https://user-images.githubusercontent.com/20355423/221371075-4aba484b-591a-4614-8da5-94df8210874a.png)

**Comment by jj248** [comment]
There you go, pushing to testing.
![image](https://user-images.githubusercontent.com/26043074/221384643-2101c476-319c-473e-a66f-5e7e6a9e3653.png)

**Comment by savagesach** [comment]
The decision works as intended, I especially like how you only need the title rather than controlling the entire duchy. I think this issue can be closed
![image](https://user-images.githubusercontent.com/86676697/221400097-b5de1561-a3b7-45db-881c-4b742d26a2f8.png)
![image](https://user-images.githubusercontent.com/86676697/221400114-f0406f8a-6bf9-4fc1-ac92-0172ef482cea.png)
