### ISSUE TITLE
Remove +30 opinion of Cannibal trait for Orcs

### ISSUE THREAD

**Issue by Gseg** [MattTheLegoman/RealmsInExile#88]
A lot of orcs are cannibals -> A lot of orcs have high opinion between them -> They all live happily eating flesh! :(

**Comment by RedArkady** [comment]
Yeah cannibals always like each other, and for *roughly* half of cannibal characters it's clearly the deciding factor in most relationships - for some its pretty much all. My instinct is to tone it down to +10. Disclaimer - I'm not sure I'm very good at judging this sort of balancing. Maybe you just want all cannibals to like each other because they're a weird subculture? That feels quite orkish.

**Comment by Gseg** [comment]
Reduced to +10 and closing!
